# Justfile for gym-timer

default:
    @just --list

# One-time setup after clone (run this first!)
setup:
    #!/usr/bin/env bash
    echo "🔧 Setting up development environment..."

    # Install npm dependencies
    npm install
    echo "✓ npm dependencies installed"

    # Generate icons if needed
    if [ ! -f "public/icons/icon-192.png" ]; then
        just icons
        echo "✓ Icons generated"
    fi

    # Generate version info
    just generate-version
    echo "✓ Version info generated"

    echo ""
    echo "✅ Setup complete! Run 'just dev' to start developing."

# Generate version info from git
generate-version:
    #!/usr/bin/env bash
    SHA=$(git rev-parse HEAD 2>/dev/null || echo "development")
    BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
    REPO_URL=$(git remote get-url origin 2>/dev/null | sed 's/\.git$//' | sed 's|git@github.com:|https://github.com/|' | sed 's|https://[^@]*@|https://|' || echo "https://github.com/user/repo")
    COMMIT_URL="$REPO_URL/commit/$SHA"
    CURRENT_URL="$REPO_URL/tree/$BRANCH"
    BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    echo "// Auto-generated by just generate-version" > src/generated_version.ts
    echo "export const GIT_SHA = \"$SHA\";" >> src/generated_version.ts
    echo "export const GIT_COMMIT_URL = \"$COMMIT_URL\";" >> src/generated_version.ts
    echo "export const GIT_CURRENT_URL = \"$CURRENT_URL\";" >> src/generated_version.ts
    echo "export const GIT_BRANCH = \"$BRANCH\";" >> src/generated_version.ts
    echo "export const BUILD_TIMESTAMP = \"$BUILD_TIME\";" >> src/generated_version.ts

# Run the development server (generates version first)
dev: generate-version
    npm run dev

# Build for production (generates version first)
build: generate-version
    npm run build

# Preview production build
preview:
    npm run preview

# Run unit tests
test:
    npm run test

# Run tests in watch mode
test-watch:
    npm run test:watch

# Generate PNG icons from SVG
icons:
    npm run icons

# Deploy to surge.sh (production) - runs test and build first
deploy: test build
    npx surge dist igor-gym-timer.surge.sh

# Deploy to surge.sh (staging)
deploy-stage: test build
    npx surge dist igor-gym-timer-stage.surge.sh

# Deploy to surge.sh (production) - alias for deploy
deploy-prod: deploy

# Clean build artifacts
clean:
    rm -rf dist node_modules/.vite

# Type check
typecheck:
    npx tsc --noEmit

# Run all checks (type check + tests)
check: typecheck test
