#!/usr/bin/env node
/**
 * Generate version info from git
 * Creates src/generated_version.ts with build metadata
 */

import { execSync } from "child_process";
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");

function execGit(cmd) {
	try {
		return execSync(cmd, { cwd: rootDir, encoding: "utf8" }).trim();
	} catch {
		return null;
	}
}

const sha = execGit("git rev-parse HEAD") || "development";
const branch = execGit("git rev-parse --abbrev-ref HEAD") || "unknown";

let repoUrl = execGit("git remote get-url origin") || "https://github.com/user/repo";
// Normalize git URL to https
repoUrl = repoUrl
	.replace(/\.git$/, "")
	.replace(/^git@github\.com:/, "https://github.com/")
	.replace(/^https:\/\/[^@]*@/, "https://");

const commitUrl = `${repoUrl}/commit/${sha}`;
const currentUrl = `${repoUrl}/tree/${branch}`;
const buildTime = new Date().toISOString();

const content = `// Auto-generated by scripts/generate-version.js
export const GIT_SHA = "${sha}";
export const GIT_COMMIT_URL = "${commitUrl}";
export const GIT_CURRENT_URL = "${currentUrl}";
export const GIT_BRANCH = "${branch}";
export const BUILD_TIMESTAMP = "${buildTime}";
`;

const outPath = join(rootDir, "src", "generated_version.ts");
writeFileSync(outPath, content);
console.log(`Generated ${outPath}`);
